require("sm0/export_helpers_sm0_confed")
--require("sm0/export_helpers_sm0_mixed_lores")
--require("sm0/export_helpers_sm0_fay")
require("sm0/export_helpers_sm0_abandon")
require("sm0/export_helpers_sm0_save_cam")
require("sm0/table_save")
--require("sm0/temp")
require("sm0/export_helpers_sm0_hidden_legendaries")
require("sm0/export_helpers_sm0_mixedLores")
require("sm0/ml_tables/ml_wh2_main_lzd_lord_mazdamundi")
require("sm0/ml_tables/ml_wh2_main_lzd_slann_mage_priest")
--require("C:/Program Files (x86)/Steam/steamapps/common/Total War WARHAMMER II/data/script/export_helpers_sm0_mixedLores")
--require("C:/Program Files (x86)/Steam/steamapps/common/Total War WARHAMMER II/data/script/ml_tables/ml_wh2_main_lzd_lord_mazdamundi")
--require("sm0/ml_log")