require("sm0/export_helpers_sm0_confed")
require("sm0/export_helpers_sm0_abandon")
require("sm0/export_helpers_sm0_save_cam")
require("sm0/table_save")
--require("sm0/sm0_test")
--require("sm0/temp")
require("sm0/export_helpers_sm0_hidden_legendaries")

--require("sm0/export_helpers_sm0_mixedLores")
require("sm0/ml_tables/ml_wh2_main_lzd_lord_mazdamundi")
require("sm0/ml_tables/ml_wh2_main_lzd_slann_mage_priest")
require("sm0/ml_tables/ml_wh2_main_def_morathi")
require("sm0/ml_tables/ml_wh2_main_hef_teclis")
require("sm0/ml_tables/ml_wh2_dlc10_hef_alarielle")
require("sm0/ml_tables/ml_chs_archaon")
require("sm0/ml_tables/ml_dlc03_bst_malagor")
require("sm0/ml_tables/ml_dlc07_brt_fay_enchantress")
--require("sm0/ml_coloured_text_button")

require("C:/Program Files (x86)/Steam/steamapps/common/Total War WARHAMMER II/data/script/export_helpers_sm0_mixedLores")
--require("sm0/ml_log")