-- Save Camera Settings
--# assume global class TABLE
--# assume TABLE.save: function(tbl: table, filename: string) --> string
--# assume TABLE.load: function(sfile: string) --> (map<string, map<string, string>>, string)